#!/bin/bash

# If running in developer mode we will start the SSH server
if [ ! -f /data/postgresql/postgresql.conf ]
  then
    mkdir -p /data/postgresql && chown -R postgres:postgres /data/postgresql
    su -c '/usr/lib/postgresql/9.3/bin/initdb -D /data/postgresql' postgres
    echo "host all  all    0.0.0.0/0  md5" >> /data/postgresql/pg_hba.conf
    echo "listen_addresses='*'" >> /data/postgresql/postgresql.conf
    su -c '/usr/lib/postgresql/9.3/bin/postgres -D /data/postgresql -c config_file=/data/postgresql/postgresql.conf' postgres &
	sleep 5
	cd /tmp
    su -c 'createdb -T template0 -E utf8 odoo' postgres
    psql --command "UPDATE pg_database set datistemplate = TRUE where datname = 'odoo';" -U postgres
    kill -9 $(ps -ef | grep '/bin/postgres -D /data/postgresql' | awk '{print $2}')
fi
su -c '/usr/lib/postgresql/9.3/bin/postgres -D /data/postgresql -c config_file=/data/postgresql/postgresql.conf' postgres
